[package]
name = "clippy-reviewdog-filter"
version = "0.1.1"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
clap = "2.33.0"
semver = "0.9.0"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
xml-rs = "0.8.0"
